### ISSUE TITLE
java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by Nandaka** [calvinaquino/LNReader-Android#182]
Need to add exception handling

``` JAVA
java.lang.IllegalArgumentException: pointerIndex out of range
at android.view.MotionEvent.nativeGetAxisValue(Native Method)
at android.view.MotionEvent.getX(MotionEvent.java:1981)
at com.erakk.lnreader.helper.NonLeakingWebView.checkZoomEvent(NonLeakingWebView.java:216)
at com.erakk.lnreader.helper.NonLeakingWebView.onTouchEvent(NonLeakingWebView.java:141)
```

**Comment by Nandaka** [comment]
``` java
java.lang.ArrayIndexOutOfBoundsException
at android.view.MotionEvent.getX(MotionEvent.java:889)
at com.erakk.lnreader.helper.NonLeakingWebView.checkZoomEvent(NonLeakingWebView.java:219)
at com.erakk.lnreader.helper.NonLeakingWebView.onTouchEvent(NonLeakingWebView.java:141)
at android.view.View.dispatchTouchEvent(View.java:3885)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:903)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1813)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1168)
at android.app.Activity.dispatchTouchEvent(Activity.java:2099)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1797)
at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2229)
at android.view.ViewRoot.handleMessage(ViewRoot.java:1888)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3687)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
at dalvik.system.NativeStart.main(Native Method)
```
