### ISSUE TITLE
java.lang.NullPointerException on some method.

### ISSUE THREAD

**Issue by Nandaka** [calvinaquino/LNReader-Android#183]
```
java.lang.NullPointerException
at com.erakk.lnreader.helper.WebArchiveReader.loadToWebView(WebArchiveReader.java:101)
at com.erakk.lnreader.task.LoadWacTask.onPostExecute(LoadWacTask.java:101)
at com.erakk.lnreader.task.LoadWacTask.onPostExecute(LoadWacTask.java:21)
```

```
java.lang.NullPointerException
at android.webkit.WebViewClassic.loadUrlImpl(WebViewClassic.java:2562)
at android.webkit.WebViewClassic.loadUrlImpl(WebViewClassic.java:2578)
at android.webkit.WebViewClassic.loadUrl(WebViewClassic.java:2571)
at android.webkit.WebView.loadUrl(WebView.java:773)
at com.erakk.lnreader.activity.DisplayLightNovelContentActivity$6.run(DisplayLightNovelContentActivity.java:986)
```

```
java.lang.NullPointerException
at com.erakk.lnreader.helper.BakaTsukiWebViewClient.shouldOverrideUrlLoading(BakaTsukiWebViewClient.java:92)
at android.webkit.CallbackProxy.uiOverrideUrlLoading(CallbackProxy.java:274)
at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:376)
```

**Comment by Nandaka** [comment]
java.lang.RuntimeException: Unable to pause activity {com.erakk.lnreader/com.erakk.lnreader.activity.DisplayLightNovelContentActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.erakk.lnreader.service.TtsService$TtsBinder.initConfig()' on a null object reference
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3805)
at android.app.ActivityThread.access$900(ActivityThread.java:139)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1216)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5086)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.erakk.lnreader.service.TtsService$TtsBinder.initConfig()' on a null object reference
at com.erakk.lnreader.helper.DisplayNovelContentTTSHelper.getTtsBinder(DisplayNovelContentTTSHelper.java:37)
at com.erakk.lnreader.helper.DisplayNovelContentTTSHelper.stop(DisplayNovelContentTTSHelper.java:49)
at com.erakk.lnreader.activity.DisplayLightNovelContentActivity.onPause(DisplayLightNovelContentActivity.java:257)
at android.app.Activity.performPause(Activity.java:5352)
at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1256)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2277)

**Comment by tianfengjingjing** [comment]
how did u fixed this ?

**Comment by Nandaka** [comment]
you can check the changes/diff, mostly just add exception handling.

**Comment by tianfengjingjing** [comment]
you can try catch throwable .To solve this problem.Because on this occasion , the callback has no sense . The only thing to care it not to crash .

**Comment by Nandaka** [comment]
that's what I do. You can check the commit/diff

**Comment by tianfengjingjing** [comment]
got cha
