### ISSUE TITLE
Settings crash on 4.0.4

### ISSUE THREAD

**Issue by yaminorito** [calvinaquino/LNReader-Android#205]
Here's the log of ICS.
Yes, they're really blank there:
```
07-26 10:45:17.829 D/class com.erakk.lnreader.AlternativeLanguageInfo(16135): Language added: language = Français, category = French, markerSynopsis = #Synopsis, parserInfo = {_par,Texte_Intégral,Full_Text,Série_,série_,Tome_,tome_,Histoire_,histoire_,Histoires_,histoires_,Side_Stor,Short_Stor,Material}
07-26 10:45:17.849 D/class com.erakk.lnreader.helper.DBHelper(16135): DB Path : /mnt/sdcard/Android/data/com.erakk.lnreader/files/databases/pages.db
07-26 10:45:18.059 I/ActivityManager(  292): Displayed com.erakk.lnreader/.UI.activity.DisplaySettingsActivity: +423ms
>> 07-26 10:45:19.839 E/AndroidRuntime(16135): 	at com.erakk.lnreader.UI.activity.DisplaySettingsActivity.setUpNestedScreen(DisplaySettingsActivity.java:108)
>> 07-26 10:45:19.839 E/AndroidRuntime(16135): 	at com.erakk.lnreader.UI.activity.DisplaySettingsActivity.onPreferenceTreeClick(DisplaySettingsActivity.java:90)
07-26 10:45:19.849 W/ActivityManager(  292):   Force finishing activity com.erakk.lnreader/.UI.activity.DisplaySettingsActivity
07-26 10:45:20.389 W/ActivityManager(  292): Activity pause timeout for ActivityRecord{41ddea20 com.erakk.lnreader/.UI.activity.DisplaySettingsActivity}
07-26 10:45:21.659 I/WindowManager(  292): WIN DEATH: Window{41da0b88 com.erakk.lnreader/com.erakk.lnreader.UI.activity.MainActivity paused=false}
07-26 10:45:21.659 I/ActivityManager(  292): Process com.erakk.lnreader (pid 16135) has died.
07-26 10:45:21.669 I/WindowManager(  292): WIN DEATH: Window{41ebcc68 com.erakk.lnreader/com.erakk.lnreader.UI.activity.NovelListContainerActivity paused=false}
07-26 10:45:21.669 I/WindowManager(  292): WIN DEATH: Window{41b91e98 com.erakk.lnreader/com.erakk.lnreader.UI.activity.DisplaySettingsActivity paused=false}
07-26 10:45:21.679 W/ActivityManager(  292): Force removing ActivityRecord{4167d1d8 com.erakk.lnreader/.UI.activity.NovelListContainerActivity}: app died, no saved state
```

**Comment by Nandaka** [comment]
Not even an exception message?

**Comment by yaminorito** [comment]
Yes it's exactly like that, whenever I try opening anything under "Preferences" section of "Settings" screen the same error crashes bakareader. I used catlog to record the log. Maybe later I'll try logging it thru Android Studio adb connection, but it'll probably be the same.

**Comment by Nandaka** [comment]
this is the offending line:
https://github.com/calvinaquino/LNReader-Android/blob/master/app/src/main/java/com/erakk/lnreader/UI/activity/DisplaySettingsActivity.java#L108

either it cannot cast the ui to linear layout or it doesn't have parent...

you are using tablet or phone?

**Comment by yaminorito** [comment]
I'm using a phone.

**Comment by Nandaka** [comment]
Try https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.34-beta1

**Comment by yaminorito** [comment]
I haven't updated to 1.1.34-beta1 yet and tried logging thru Android Studio adb and I finally got the complete error message:
```
07-28 19:01:28.110    5103-5103/com.erakk.lnreader E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at com.erakk.lnreader.UI.activity.DisplaySettingsActivity.setUpNestedScreen(DisplaySettingsActivity.java:108)
            at com.erakk.lnreader.UI.activity.DisplaySettingsActivity.onPreferenceTreeClick(DisplaySettingsActivity.java:90)
            at android.preference.Preference.performClick(Preference.java:949)
            at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:202)
            at android.widget.AdapterView.performItemClick(AdapterView.java:292)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1058)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:2514)
            at android.widget.AbsListView$1.run(AbsListView.java:3168)
            at android.os.Handler.handleCallback(Handler.java:605)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4482)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by yaminorito** [comment]
It's still there after updating.
Here's the log:
```
07-28 19:15:10.879  13230-13230/com.erakk.lnreader D/class com.erakk.lnreader.AlternativeLanguageInfo﹕ Language added: language = Bahasa Indonesia, category = Indonesian, markerSynopsis = #Sinopsis_Cerita, parserInfo = {_oleh,Full_Text,Serial_,serial_,Seri_,seri_,Cerita_Tambah,Cerita_Singkat,Cerita_Pendek,Side_Stor,Short_Stor}
07-28 19:15:10.879  13230-13230/com.erakk.lnreader D/class com.erakk.lnreader.AlternativeLanguageInfo﹕ Language added: language = Polish, category = Polish, markerSynopsis = #Streszczenie_fabu.C5.82y, parserInfo = {_autorstwa,Pe.C5.82ny_tekst,Seria_,seria_,Cerita_Tambah,Historie_poboczne,Historie_Poboczne,Historie_kr.C3.B3tki,Historie_Kr.C3.B3tki,Side_Stor,Short_Stor}
07-28 19:15:10.889  13230-13230/com.erakk.lnreader D/class com.erakk.lnreader.AlternativeLanguageInfo﹕ Language added: language = Français, category = French, markerSynopsis = #Synopsis, parserInfo = {_par,Texte_Intégral,Full_Text,Série_,série_,Tome_,tome_,Histoire_,histoire_,Histoires_,histoires_,Side_Stor,Short_Stor,Material}
07-28 19:15:10.929  13230-13230/com.erakk.lnreader D/class com.erakk.lnreader.helper.DBHelper﹕ DB Path : /mnt/sdcard/Android/data/com.erakk.lnreader/files/databases/pages.db
07-28 19:15:13.409  13230-13230/com.erakk.lnreader D/class com.erakk.lnreader.UIHelper﹕ Locale: en
07-28 19:15:13.419  13230-13230/com.erakk.lnreader W/class com.erakk.lnreader.UI.activity.BaseActivity﹕ No toolbar detected!
07-28 19:15:13.439  13230-13230/com.erakk.lnreader D/class com.erakk.lnreader.UI.activity.DisplayChangelogActivity﹕ created
07-28 19:15:33.269  13230-13230/com.erakk.lnreader W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40b18390)
07-28 19:15:33.269  13230-13230/com.erakk.lnreader E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at com.erakk.lnreader.UI.activity.DisplaySettingsActivity.setUpNestedScreen(DisplaySettingsActivity.java:110)
            at com.erakk.lnreader.UI.activity.DisplaySettingsActivity.onPreferenceTreeClick(DisplaySettingsActivity.java:92)
            at android.preference.Preference.performClick(Preference.java:949)
            at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:202)
            at android.widget.AdapterView.performItemClick(AdapterView.java:292)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1058)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:2514)
            at android.widget.AbsListView$1.run(AbsListView.java:3168)
            at android.os.Handler.handleCallback(Handler.java:605)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4482)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Nandaka** [comment]
Can I get your device details?

**Comment by yaminorito** [comment]
A rebranded clone of this www.antelife.com/innos-d9-msm8225-1-2ghz-android-4-0-smartphone-4-3-inch-rom-4gb-black.html

**Comment by Nandaka** [comment]
Try this: https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.34

**Comment by yaminorito** [comment]
Working now. Thank you.
