### ISSUE TITLE
Window leak

### ISSUE THREAD

**Issue by yaminorito** [calvinaquino/LNReader-Android#206]
I found this while testing on Kitkat 4.4.2.
I was opening a chapter, finishing it, then pressed back button.
I'm not sure if it's harmful or not....

```
07-26 11:07:28.005  13078-13078/com.erakk.lnreader D/class com.erakk.lnreader.UI.activity.DisplayLightNovelContentAct﹕ onPause Completed
07-26 11:07:28.005  13078-13078/com.erakk.lnreader D/ActivityThread﹕ ACT-AM_ON_PAUSE_CALLED ActivityRecord{4252ab60 token=android.os.BinderProxy@4252a2c0 {com.erakk.lnreader/com.erakk.lnreader.UI.activity.DisplayLightNovelContentActivity}}
07-26 11:07:28.006  13078-14902/com.erakk.lnreader D/dalvikvm﹕ threadid=25: notify debugger
07-26 11:07:28.006  13078-14902/com.erakk.lnreader D/dalvikvm﹕ threadid=25 (Thread-1066): calling run()
07-26 11:07:28.006  13078-14902/com.erakk.lnreader I/class com.erakk.lnreader.UI.activity.DisplayLightNovelContentAct﹕ Complete Read PageModel for Content: Campione!:Volume_1_Chapter4 check value: 63327.0 <= 63327
07-26 11:07:28.013  13078-13078/com.erakk.lnreader D/ActivityThread﹕ ACT-PAUSE_ACTIVITY_FINISHING handled : 0 / android.os.BinderProxy@4252a2c0
07-26 11:07:28.019  13078-13078/com.erakk.lnreader D/class com.erakk.lnreader.UI.fragment.DisplayLightNovelDetailsFra﹕ OnResume: FINISHED
07-26 11:07:28.020  13078-13078/com.erakk.lnreader D/dalvikvm﹕ create interp thread : stack size=128KB
07-26 11:07:28.020  13078-13078/com.erakk.lnreader D/dalvikvm﹕ create new thread
07-26 11:07:28.020  13078-13078/com.erakk.lnreader D/dalvikvm﹕ new thread created
07-26 11:07:28.020  13078-13078/com.erakk.lnreader D/dalvikvm﹕ update thread list
07-26 11:07:28.020  13078-14904/com.erakk.lnreader D/dalvikvm﹕ threadid=26: interp stack at 0x64db2000
07-26 11:07:28.020  13078-14904/com.erakk.lnreader D/dalvikvm﹕ threadid=26: created from interp
07-26 11:07:28.020  13078-13078/com.erakk.lnreader D/dalvikvm﹕ start new thread
07-26 11:07:28.021  13078-13078/com.erakk.lnreader D/ActivityThread﹕ ACT-AM_ON_RESUME_CALLED ActivityRecord{421c6df0 token=android.os.BinderProxy@4219ad80 {com.erakk.lnreader/com.erakk.lnreader.UI.activity.NovelListContainerActivity}}
07-26 11:07:28.021  13078-14904/com.erakk.lnreader D/dalvikvm﹕ threadid=26: notify debugger
07-26 11:07:28.021  13078-14904/com.erakk.lnreader D/dalvikvm﹕ threadid=26 (Thread-1067): calling run()
07-26 11:07:28.024  13078-13078/com.erakk.lnreader D/ActivityThread﹕ ACT-RESUME_ACTIVITY handled : 0 / android.os.BinderProxy@4219ad80
07-26 11:07:28.054  13078-13078/com.erakk.lnreader D/GraphicBuffer﹕ create handle(0x65811de8) (w:480, h:800, f:1)
07-26 11:07:28.055  13078-13078/com.erakk.lnreader I/MaliEGL﹕ [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1
07-26 11:07:28.055  13078-13078/com.erakk.lnreader I/MaliEGL﹕ [Mali]max_allowed_dequeued_buffers=3
07-26 11:07:28.055  13078-13078/com.erakk.lnreader D/GraphicBuffer﹕ close handle(0x65811de8) (w:480 h:800 f:1)
07-26 11:07:28.063  13078-13078/com.erakk.lnreader D/GraphicBuffer﹕ create handle(0x65811de8) (w:480, h:800, f:1)
07-26 11:07:28.064  13078-13078/com.erakk.lnreader D/OpenGLRenderer﹕ setViewport 480x800 <0x5ff992a0>
07-26 11:07:28.092  13078-13078/com.erakk.lnreader D/OpenGLRenderer﹕ prepareDirty (0.00, 0.00, 480.00, 800.00) opaque 1 <0x5ff992a0>
07-26 11:07:28.094  13078-13078/com.erakk.lnreader D/OpenGLRenderer﹕ finish <0x5ff992a0>
07-26 11:07:28.103  13078-13078/com.erakk.lnreader D/AbsListView﹕ onWindowFocusChanged: hasWindowFocus=true, this=android.widget.ExpandableListView{421bbae8 VFED.VCL .F...... 0,0-480,678 #7f0b007f app:id/chapter_list}
07-26 11:07:28.104  13078-13078/com.erakk.lnreader D/AbsListView﹕ onWindowFocusChanged: hasWindowFocus=true, this=android.support.design.internal.NavigationMenuView{420a1e88 VFED..C. ......ID 0,0-384,762}
07-26 11:07:28.111  13078-14902/com.erakk.lnreader D/class com.erakk.lnreader.helper.db.PageModelHelper﹕ Page Model: Campione!:Volume_1_Chapter4 Updated, Affected Row: 1
07-26 11:07:28.121  13078-13078/com.erakk.lnreader D/AbsListView﹕ onWindowFocusChanged: hasWindowFocus=false, this=android.support.design.internal.NavigationMenuView{4222ee40 VFED..C. ......ID 0,0-384,762}
07-26 11:07:28.140  13078-13078/com.erakk.lnreader D/OpenGLRenderer﹕ Flushing caches (mode 0)
07-26 11:07:28.141  13078-13078/com.erakk.lnreader D/GraphicBuffer﹕ close handle(0x6587edb0) (w:480 h:800 f:1)
07-26 11:07:28.142  13078-13078/com.erakk.lnreader D/GraphicBuffer﹕ close handle(0x609e0288) (w:480 h:800 f:1)
07-26 11:07:28.142  13078-13078/com.erakk.lnreader D/GraphicBuffer﹕ close handle(0x6587b410) (w:480 h:800 f:1)
07-26 11:07:28.142  13078-13078/com.erakk.lnreader D/GraphicBuffer﹕ close handle(0x65805288) (w:480 h:800 f:1)
07-26 11:07:28.153  13078-13078/com.erakk.lnreader D/GraphicBuffer﹕ create handle(0x60906ce0) (w:480, h:73, f:1)
07-26 11:07:28.156  13078-13078/com.erakk.lnreader D/OpenGLRenderer﹕ Flushing caches (mode 0)
07-26 11:07:28.159  13078-13078/com.erakk.lnreader D/GraphicBuffer﹕ close handle(0x62b8cb68) (w:480 h:73 f:1)
07-26 11:07:28.159  13078-13078/com.erakk.lnreader D/GraphicBuffer﹕ close handle(0x60906ce0) (w:480 h:73 f:1)
07-26 11:07:28.367  13078-14902/com.erakk.lnreader I/class com.erakk.lnreader.helper.db.NovelContentUserHelperModel﹕ Novel Content:Campione!:Volume_1_Chapter4 Updated, Affected Row: 1
07-26 11:07:28.371  13078-14902/com.erakk.lnreader D/class com.erakk.lnreader.UI.activity.DisplayLightNovelContentAct﹕ Update Content:X=0:Y=416:Z=1.5
07-26 11:07:28.388  13078-14902/com.erakk.lnreader I/class com.erakk.lnreader.UI.activity.DisplayLightNovelContentAct﹕ Last Read State Update complete: Campione!:Volume_1_Chapter4
07-26 11:07:28.388  13078-14902/com.erakk.lnreader D/dalvikvm﹕ threadid=25: exiting
07-26 11:07:28.388  13078-14902/com.erakk.lnreader D/dalvikvm﹕ threadid=25: bye!
07-26 11:07:28.447  13078-13078/com.erakk.lnreader D/class com.erakk.lnreader.UI.activity.DisplayLightNovelContentAct﹕ onStop Completed
07-26 11:07:28.452  13078-14026/com.erakk.lnreader D/dalvikvm﹕ threadid=24: bye!
07-26 11:07:28.453  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x62b71888)
07-26 11:07:28.453  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x6637ffb8)
07-26 11:07:28.453  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:64 h:512 f:1) handle(0x6637fca8)
07-26 11:07:28.453  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x6581fad8)
07-26 11:07:28.453  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x62b7e408)
07-26 11:07:28.454  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x608fdda0)
07-26 11:07:28.454  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x6579bd50)
07-26 11:07:28.454  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x6579b918)
07-26 11:07:28.454  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x65798468)
07-26 11:07:28.454  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x665cbf80)
07-26 11:07:28.455  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x665cb578)
07-26 11:07:28.455  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x665ca880)
07-26 11:07:28.455  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x665aa560)
07-26 11:07:28.455  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:64 h:512 f:1) handle(0x6637efb0)
07-26 11:07:28.455  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x613d5d60)
07-26 11:07:28.456  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x60ceee40)
07-26 11:07:28.456  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x60ce9878)
07-26 11:07:28.456  13078-13078/com.erakk.lnreader I/GraphicBuffer﹕ free buffer (w:384 h:384 f:1) handle(0x60ce8b80)
07-26 11:07:28.468  13078-13078/com.erakk.lnreader D/OpenGLRenderer﹕ Flushing caches (mode 0)
07-26 11:07:28.469  13078-13078/com.erakk.lnreader D/WebView﹕ destroy
07-26 11:07:28.472  13078-13078/com.erakk.lnreader D/OpenGLRenderer﹕ Flushing caches (mode 0)
07-26 11:07:28.508  13078-13078/com.erakk.lnreader E/WindowManager﹕ android.view.WindowLeaked: Activity com.erakk.lnreader.UI.activity.DisplayLightNovelContentActivity has leaked window android.widget.ZoomButtonsController$Container{422cb888 V.E..... ......I. 0,0-480,73} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:425)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:250)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.widget.ZoomButtonsController.setVisible(ZoomButtonsController.java:371)
            at com.android.org.chromium.android_webview.AwZoomControls.invokeZoomPicker(AwZoomControls.java:28)
            at com.android.org.chromium.content.browser.ContentViewCore.invokeZoomPicker(ContentViewCore.java:2629)
            at com.android.org.chromium.content.browser.ContentViewGestureHandler$1.onScroll(ContentViewGestureHandler.java:429)
            at com.android.org.chromium.content.browser.third_party.GestureDetector.onTouchEvent(GestureDetector.java:582)
            at com.android.org.chromium.content.browser.ContentViewGestureHandler.processTouchEvent(ContentViewGestureHandler.java:970)
            at com.android.org.chromium.content.browser.ContentViewGestureHandler.onTouchEvent(ContentViewGestureHandler.java:802)
            at com.android.org.chromium.content.browser.ContentViewCore.onTouchEvent(ContentViewCore.java:1243)
            at com.android.org.chromium.android_webview.AwContents.onTouchEvent(AwContents.java:1580)
            at com.android.webview.chromium.WebViewChromium.onTouchEvent(WebViewChromium.java:1853)
            at android.webkit.WebView.onTouchEvent(WebView.java:2176)
            at com.erakk.lnreader.helper.NonLeakingWebView.onTouchEvent(NonLeakingWebView.java:142)
            at android.view.View.dispatchTouchEvent(View.java:7782)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2316)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2013)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2109)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1541)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2520)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2057)
            at android.view.View.dispatchPointerEvent(View.java:7973)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4392)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4263)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3809)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3859)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3828)
            at androi...
```

**Comment by Nandaka** [comment]
may need to implement this: http://stackoverflow.com/a/28455240

**Comment by Nandaka** [comment]
I can't fix this one, I think bug from the WebView itself.

What I can do is by disabling the zoom control visibility, the zoom function still works using 2 finger pinch.

**Comment by yaminorito** [comment]
Maybe adding "Not Recommended" or a warning on the "Show Zoom Control" description would suffice for now. Although I myself don't use zoom buttons since pinching is enough for that, there might be others.

**Comment by Nandaka** [comment]
hmm, I'll just disable first and let other complain later  :smiling_imp:

**Comment by yaminorito** [comment]
:smiling_imp::+1:

**Comment by Nandaka** [comment]
Try https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.34-beta1
